version: '3'
services:

  etcd:
    image: quay.io/coreos/etcd:v3.5.4
    volumes:
      - ./volumes/etcd:/etcd-data
    ports:
      - 2379:2379
      - 2380:2380
    entrypoint: /usr/local/bin/etcd
    command:
      - --name=etcd-1
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
      - --data-dir=/etcd-data
      - --max-txn-ops=4096
      - --quota-backend-bytes=34359738368
      - --log-level=warn
